### ISSUE TITLE
Evernote - Markdown not rendering on common tags

### ISSUE THREAD

**Issue by karlgo** [kotfu/marked-bonus-pack#5]
I had an issue getting the script for Evernote to create the 'Marked Preview.md'

This issue surrounded having the correct path to the Evernote database. This ended up being the following path, minus my user specific number. (See Evernote: Help (holding down option) | Troubleshooting | Open Database Folder)
~/Library/Containers/com.evernote.Evernote/Data/Library/Application Support/com.evernote.Evernote/accounts/www.evernote.com/

Once this was complete, I'm finding that headers are not rendering in Marked. **Bold** and *Italics* do render.

Any ideas?

**Comment by kotfu** [comment]
So two problems here right?

1. Path in the everwatch.rb isn't pointing to where your evernote data actually is. It appears you are using Evernote downloaded from the App Store, instead of Evernote downloaded from the evernote.com website. Is this a correct assumption?

2. Markdown headers are not rendering correctly. Can you post an example of a markdown document that isn't rendering?

**Comment by kotfu** [comment]
I think I've got both things fixed. Try with the latest code and let me know if it works for you.
